general.import = ["~/.config/alacritty/dracula.toml"]
general.live_config_reload = true

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/zsh"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window]
option_as_alt = 'Both'
decorations = 'Buttonless'
startup_mode = 'Windowed'
dynamic_title = true
decorations_theme_variant = 'Dark'

[window.dimensions]
columns = 154
lines = 45

[window.padding]
x = 10
y = 10
